"use client";

import { useCallback, useEffect, useState } from "react";
import { Check, CircleDollarSign, ClipboardCheck, Plus, RefreshCw, Truck, Users } from "lucide-react";
import Swal from "@/lib/swal";

type Role = "SUPER_ADMIN" | "TENANT_ADMIN" | "DRIVER" | "CUSTOMER";
type Row = Record<string, unknown>;
const pageCache = new Map<string, Row[]>();
const cash = (v: unknown) => `INR ${Number(v ?? 0).toLocaleString("en-IN")}`;
const asDate = (v: unknown) => v ? new Date(String(v)).toLocaleString() : "â€”";

export default function OperationalPage({ page, role, onRefresh }: { page: string; role: Role; onRefresh?: () => void }) {
  const [rows, setRows] = useState<Row[]>([]); const [loading, setLoading] = useState(true); const [problem, setProblem] = useState("");
  const endpoint = page === "Customers" ? "/api/customers" : page === "Fleet Management" ? "/api/vehicles" : page === "Staff & Payroll" ? "/api/drivers" : page === "Payroll" ? "/api/payroll" : page === "Trip Expenses" || page === "My Trip Expenses" ? "/api/expenses" : page === "POD / Deliveries" || page === "POD / Delivery Closure" ? "/api/pod" : "/api/trips";
  const load = useCallback(async () => { const cached = pageCache.get(endpoint); if (cached) { setRows(cached); setLoading(false); } else setLoading(true); try { const r = await fetch(endpoint, { cache: "no-store" }); const b = await r.json(); if (!r.ok) throw new Error(b.error); const nextRows = b.data ?? []; pageCache.set(endpoint, nextRows); setRows(nextRows); setProblem(""); } catch (e) { setProblem(e instanceof Error ? e.message : "Could not load records."); } finally { setLoading(false); } }, [endpoint]);
  useEffect(() => { void load(); }, [load]);

  async function addCustomer() {
    const { value } = await Swal.fire({ title: "Add customer", html: `<div class="swal-form"><label>Business / customer name<input id="op-name"></label><label>Email<input id="op-email" type="email"></label><label>Phone<input id="op-phone"></label><label>Address<input id="op-address"></label><label>GSTIN<input id="op-gstin"></label><label>Login password (optional)<input id="op-password" type="password"></label></div>`, showCancelButton: true, confirmButtonText: "Save customer", preConfirm: () => { const name = (document.getElementById("op-name") as HTMLInputElement).value.trim(); const email = (document.getElementById("op-email") as HTMLInputElement).value.trim(); const phone = (document.getElementById("op-phone") as HTMLInputElement).value.trim(); const password = (document.getElementById("op-password") as HTMLInputElement).value; if (!name || (!email && !phone) || (password && password.length < 10)) { Swal.showValidationMessage("Add a name, email or phone. Login password must be 10+ characters."); return; } return { name, email, phone, address: (document.getElementById("op-address") as HTMLInputElement).value, gstin: (document.getElementById("op-gstin") as HTMLInputElement).value, password, createLogin: Boolean(password) }; } });
    if (!value) return; await post("/api/customers", value, load);
  }

  async function addExpense() {
    const trips = await fetch("/api/trips").then(async r => r.ok ? (await r.json()).data as Row[] : []);
    const { value } = await Swal.fire({ title: "Submit trip expense", html: `<div class="swal-form"><label>Trip<select id="op-trip">${trips.map(t => `<option value="${String(t.reference)}">${String(t.reference)} Â· ${String(t.origin)} to ${String(t.destination)}</option>`).join("")}</select></label><label>Category<input id="op-category" placeholder="Fuel, toll, food"></label><label>Amount<input id="op-amount" type="number" min="1"></label><label>Note<input id="op-note"></label></div>`, showCancelButton: true, confirmButtonText: "Submit expense", preConfirm: () => { const amount = Number((document.getElementById("op-amount") as HTMLInputElement).value); const category = (document.getElementById("op-category") as HTMLInputElement).value.trim(); if (!category || amount <= 0) { Swal.showValidationMessage("Enter category and a positive amount."); return; } return { tripReference: (document.getElementById("op-trip") as HTMLSelectElement).value, category, amount, note: (document.getElementById("op-note") as HTMLInputElement).value }; } });
    if (!value) return; await post("/api/expenses", value, load);
  }

  async function addPayroll() {
    const people = await fetch("/api/users").then(async r => r.ok ? (await r.json()).data as Row[] : []);
    const { value } = await Swal.fire({ title: "Add payroll entry", html: `<div class="swal-form"><label>Employee<select id="payroll-user"><option value="">Enter name</option>${people.filter(p => p.role === "DRIVER" || p.role === "TENANT_ADMIN").map(p => `<option value="${String(p.id)}">${String(p.name)}</option>`).join("")}</select></label><label>Employee name<input id="payroll-name"></label><label>Month<input id="payroll-period" type="month"></label><label>Amount<input id="payroll-amount" type="number" min="1"></label><label>Note<input id="payroll-note"></label></div>`, showCancelButton: true, confirmButtonText: "Save payroll", didOpen: () => { const s = document.getElementById("payroll-user") as HTMLSelectElement; s.onchange = () => { const o = s.selectedOptions[0]; if (o.value) (document.getElementById("payroll-name") as HTMLInputElement).value = o.text; }; }, preConfirm: () => { const employeeName = (document.getElementById("payroll-name") as HTMLInputElement).value.trim(); const period = (document.getElementById("payroll-period") as HTMLInputElement).value; const amount = Number((document.getElementById("payroll-amount") as HTMLInputElement).value); if (!employeeName || !period || amount <= 0) { Swal.showValidationMessage("Employee, month and positive amount are required."); return; } return { userId: (document.getElementById("payroll-user") as HTMLSelectElement).value, employeeName, period, amount, note: (document.getElementById("payroll-note") as HTMLInputElement).value }; } });
    if (!value) return; await post("/api/payroll", value, load);
  }

  async function closeDelivery(row: Row) {
    const { value } = await Swal.fire({ title: `Close ${String(row.reference)}`, html: `<div class="swal-form"><label>Received by<input id="pod-recipient"></label><label>Delivery note<input id="pod-note"></label><label>Proof photo<input id="pod-image" type="file" accept="image/png,image/jpeg,image/webp"></label></div>`, showCancelButton: true, confirmButtonText: "Complete delivery", preConfirm: () => { const receivedBy = (document.getElementById("pod-recipient") as HTMLInputElement).value.trim(); const file = (document.getElementById("pod-image") as HTMLInputElement).files?.[0]; if (!receivedBy) { Swal.showValidationMessage("Recipient name is required."); return; } return new Promise<{ receivedBy: string; note: string; image?: string } | undefined>(resolve => { if (!file) return resolve({ receivedBy, note: (document.getElementById("pod-note") as HTMLInputElement).value }); if (file.size > 2 * 1024 * 1024) { Swal.showValidationMessage("Photo must be under 2 MB."); return resolve(undefined); } const reader = new FileReader(); reader.onload = () => resolve({ receivedBy, note: (document.getElementById("pod-note") as HTMLInputElement).value, image: typeof reader.result === "string" ? reader.result : undefined }); reader.readAsDataURL(file); }); } });
    if (!value) return; await post("/api/pod", { ...value, reference: row.reference }, load);
  }

  async function markExpense(row: Row, status: string) { const r = await fetch("/api/expenses", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: row.id, status }) }); const b = await r.json(); if (!r.ok) return Swal.fire({ icon: "error", title: "Could not update expense", text: b.error }); await load(); }
  const filtered = rows.filter(row => page === "Live Tracking" || page === "My Live Deliveries" ? row.status === "IN_TRANSIT" : page === "Booking Requests" ? row.status === "PENDING" : page === "Shipment Assignments" ? row.status === "PENDING" || row.status === "IN_TRANSIT" : true);
  const columns = page === "Payroll" ? ["employeeName", "period", "amount", "status", "note", "createdAt"] : page.includes("Expense") ? ["trip", "driver", "category", "amount", "status", "createdAt"] : page.includes("Deliveries") || page.includes("Closure") || page === "POD / Deliveries" ? ["reference", "customerName", "origin", "destination", "deliveredAt", "deliveryReceivedBy", "podNote", "proof"] : page === "Customers" ? ["name", "email", "phone", "gstin", "isActive"] : page === "Fleet Management" ? ["registration", "type", "capacity", "status"] : page === "Staff & Payroll" ? ["name", "email", "phone", "isActive"] : ["reference", "customerName", "origin", "destination", "driver", "vehicle", "status", "amount", "createdAt"];
  const label = (key: string) => ({ createdAt: "Created", deliveredAt: "Delivered", customerName: "Customer", isActive: "Active", trip: "Trip", driver: "Driver", vehicle: "Vehicle", deliveryReceivedBy: "Received by", podNote: "POD note", proof: "Proof photo" } as Record<string, string>)[key] ?? key.replace(/[A-Z]/g, c => ` ${c}`).replace(/^./, c => c.toUpperCase());
  const valueOf = (row: Row, key: string) => { const raw = key === "trip" ? (row.trip as Row | undefined)?.reference : key === "driver" ? (row.driver as Row | undefined)?.name ?? row.driver : key === "vehicle" ? (row.vehicle as Row | undefined)?.registration ?? row.vehicle : row[key]; if (key === "amount") return cash(raw); if (key === "createdAt" || key === "deliveredAt") return asDate(raw); if (typeof raw === "boolean") return raw ? "Active" : "Inactive"; if (raw === null || raw === undefined || raw === "") return "â€”"; return String(raw); };
  const canAddCustomer = page === "Customers" && role === "TENANT_ADMIN"; const canAddPayroll = page === "Payroll" && role === "TENANT_ADMIN"; const canAddExpense = page.includes("Expense") && ["TENANT_ADMIN", "DRIVER"].includes(role); const canClose = (page.includes("Closure") || page === "POD / Deliveries" || page === "My Live Deliveries") && ["TENANT_ADMIN", "DRIVER"].includes(role); const canStart = page === "Shipment Assignments" && role === "DRIVER";
  async function startTrip(row: Row) { const r = await fetch(`/api/trips/${encodeURIComponent(String(row.reference))}/status`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status: "IN_TRANSIT" }) }); const b = await r.json(); if (!r.ok) return Swal.fire({ icon: "error", title: "Could not start trip", text: b.error }); await load(); onRefresh?.(); }

  return <section className="panel directory-panel"><div className="panel-header table-heading"><div><h2>{page}</h2><p>{pageDescription(page)}</p></div><div className="table-actions">{canAddCustomer && <button className="button button-primary small-button" onClick={addCustomer}><Users size={15}/>Add customer</button>}{canAddExpense && <button className="button button-primary small-button" onClick={addExpense}><CircleDollarSign size={15}/>Submit expense</button>}{canAddPayroll && <button className="button button-primary small-button" onClick={addPayroll}><Plus size={15}/>Add payroll</button>}<button className="table-filter" onClick={() => void load()}><RefreshCw size={14}/>Refresh</button></div></div>{problem && <div className="empty-state">{problem}</div>}{loading ? <div className="empty-state">Loading recordsâ€¦</div> : <div className="table-scroll"><table className="data-table"><thead><tr>{columns.map(k => <th key={k}>{label(k).toUpperCase()}</th>)}{(canClose || canStart || (page.includes("Expense") && role === "TENANT_ADMIN") || canAddPayroll) && <th>ACTION</th>}</tr></thead><tbody>{filtered.map((row, i) => <tr key={String(row.id ?? row.reference ?? i)}>{columns.map(k => <td key={k}>{k === "proof" ? row.podImageData ? <a href={String(row.podImageData)} target="_blank" rel="noreferrer">View photo</a> : "No photo" : k === "status" ? <span className={`pill-status ${String(row[k]).toLowerCase().replaceAll("_", "-")}`}><i/>{valueOf(row, k)}</span> : valueOf(row, k)}</td>)}{canClose && <td>{row.status === "IN_TRANSIT" ? <button className="button button-primary small-button" onClick={() => void closeDelivery(row)}><ClipboardCheck size={14}/>Close with POD</button> : row.status === "DELIVERED" ? <span className="pill-status active"><Check size={13}/>POD saved</span> : null}</td>}{canStart && <td>{row.status === "PENDING" ? <button className="button button-primary small-button" onClick={() => void startTrip(row)}><Truck size={14}/>Start trip</button> : <span>In progress</span>}</td>}{canAddPayroll && <td>{row.status === "PAID" ? "Paid" : <button className="button button-primary small-button" onClick={async () => { const r = await fetch("/api/payroll", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: row.id }) }); if (r.ok) await load(); }}><Check size={14}/>Mark paid</button>}</td>}{page.includes("Expense") && role === "TENANT_ADMIN" && <td><select value={String(row.status)} aria-label="Expense approval" onChange={e => void markExpense(row, e.target.value)}><option value="SUBMITTED">Submitted</option><option value="APPROVED">Approve</option><option value="REJECTED">Reject</option><option value="PAID">Mark paid</option></select></td>}</tr>)}</tbody></table>{!filtered.length && <div className="empty-state"><Truck size={25}/><strong>No records yet</strong><span>{emptyHint(page)}</span></div>}</div>}</section>;
}

async function post(url: string, body: unknown, reload: () => Promise<void>) { const r = await fetch(url, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const b = await r.json(); if (!r.ok) return Swal.fire({ icon: "error", title: "Could not save", text: b.error ?? "Try again." }); await Swal.fire({ icon: "success", title: "Saved", text: "Your update has been recorded." }); await reload(); }
function pageDescription(page: string) { if (page === "Customers") return "Manage customer accounts, contacts and booking history."; if (page === "Payroll") return "Monthly salaries, approval and payout tracking."; if (page === "Fleet Management") return "Vehicles registered to this workspace."; if (page === "Staff & Payroll") return "Driver roster, contact details and activity."; if (page.includes("Expense")) return "Trip-wise driver expenses and approval status."; if (page.includes("POD") || page.includes("Deliveries")) return "Delivery closures with recipient details and proof of delivery."; if (page.includes("Tracking")) return "Current shipments in transit for this workspace."; if (page === "Booking Requests") return "Pending shipment bookings awaiting dispatch."; return "Shipment assignments and operational status."; }
function emptyHint(page: string) { if (page.includes("Expense")) return "Trip expenses will appear after submission."; if (page.includes("POD") || page.includes("Deliveries")) return "Completed deliveries and proof will appear here."; if (page === "Customers") return "Add your first customer to enable bookings."; return "Records will appear here when created."; }




